language: java
jdk:
- oraclejdk8
sudo: required
services:
- mongodb
- rabbitmq
before_install:
- echo "Testing Docker Hub credentials"
- docker -v
- docker login -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD
- echo "Docker Hub credentials are working"
after_success:
- export ACTUAL_BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH;
  else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
- echo "Test Success - Branch($TRAVIS_BRANCH) Actual($ACTUAL_BRANCH) Pull Request($TRAVIS_PULL_REQUEST)
  Tag($TRAVIS_TAG) Commit($TRAVIS_COMMIT) PR($TRAVIS_PULL_REQUEST) Build($TRAVIS_BUILD_NUMBER)"
- if [[ "$ACTUAL_BRANCH" == "master" ]]; then echo -e "Push Container to Docker Hub";
  fi
- docker login -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD
- export REPO=aista/driver-cmd
- export TAG=`if [ "$ACTUAL_BRANCH" == "master" ]; then echo "latest";else echo "";
  fi`
- docker build -f Dockerfile -t $REPO:$TAG .
- docker push $REPO
env:
  global:
  - secure: Lv1ieA/+aJBLMJULbRBmKg/zUolPB2FgmUZMGH+20xPtol7DsG+l5RElJ1AyuGiW4d6lZ5VDtNldEQDsKwJsuRLm1bQSQsEX+rlJxqN7OAgVyXsHoJRoMPtODqvnROJjQlr2UOINCYAq4wIuheSX6xS2j8gDDK94644/GNgz4wmyZAwfeatUcfHVFlc5HKf1sDWNmOJEcDaqZFPWJsTihoNn1ey3xFc9ezqNC6JclQjnAe32WLphfTuDZKVwlgLVZ7xir4BUyM8lYrjI3TkLRLElofbKqdlxEAvLfDtHpzwONoBG1ba7neDtCN9MzHgefVLBwbD2lJdQRx+OSrBRI5p9w62YNmiUoTa3qh8b5N0qDSYVo8HtXTGGZXCRddjt2VuNVWlVSnJdgOZBT1P51Vcdp7MkVRhNd3+lqhPzwG3xUiJD6Z0FSDBc9Q3CpHrkPqhBxG4ZbJ7/CVRjIz02i339Hit1PCCd5LBu4+IumbTPkP7QpXYUw9yMaVjppYC3cWviJJ/k2Xmy67NWdWpkNhHjlourfzuZIsEGx8Maj4AONlg2e4JwJ6r1Tu4r1336oObDvuxr9e7nhMi3VRDJnxrSvoIN191CrP6+sCwbSDo09gOs0QEnYwNZYTp5fgJZrDlraH0MVoK8mMy+Flh4kRWO1KA0TxADre/x59d1i4Y=
  - secure: fACBK6YwmWKa5cvXuCEScHNpMhRee0RRNOdNh+clgCHfqwxyNHkLNBw8w+zaevci3dR/Mhrmb2ehEH8MckAwYG1RwlNyN6OUDuzAin9lqjSi+Pxgj9NG/fx0tt0o3Jr4UpaMyd7j7WImvTBlxJO9S9NAPUcuQ+KKzxLJl5qDTC7oTtxjucA/rILjd1LNWT9DNQmUD3eSGjnu+bA/gb9O5QwOjPHcs4aOfYxU5DP6xUzpEVnAfTBjKJmFwyoBuE7hVBkRKa9YqXlLtQPcHEJmGHqoUDE05kF1H0y5BRcK0eo+Q098g2ogg6tD45g+XX2lwDkFH7D6Zg/s4gVVgx0023FIM/dLeQUaJ6J7y7ao1CBpd3LOc9DA08NlYdwuz096Y6EOHPAUyQcm8Isoqt77dgTr9I44B6e5YiUASngpgfYqhwg74a1Z3Fc4qux9qQJfQlcvmeKQy6V+TnMeiJhjVIIdNnWH/PXqBly5E0PBBhZFr6UIcNV/pGeYpg2T7htPDiIE3myhYTjyKYlGGdtVyodbbTLMnT71Xf0d04tG3HDn9HwO2vOYDdR2QHxXETk9ftNJOKjdrcPeAiKbgcyMXqQPM9JX8he9mYiN00Q8vK3/KWFDRBVAPoZYcD02gW2vb3hpx84RCz4wxV04wMASijvx1KbdHLd6P0GPhWELOMI=
