# Mongo config
spring:
  data:
    mongodb:
      database: driver-cmd
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
  application:
    name: driver-cmd
  rabbitmq:
    host: ${RABBIT_HOST:localhost}

server:
  port: ${APP_PORT:8080}

axon:
  cluster-name: ${spring.application.name}
  eventstore:
    mongo:
      connections:
        default:
          uri: ${mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/driver-cmd
          aggregates:
            - Trip

amqp:
  events:
    host: ${RABBIT_HOST:localhost}
    exchange-name: eventBusDriver
    queue-name: eventQueueDriver
    handlers: org.aitesting.microservices.driver.cmd.domain.eventhandlers

logging:
  level:
    root: INFO
    org:
      springframework:
        security: DEBUG
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
      hibernate: DEBUG
      apache:
        commons:
          dbcp2: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: http://discoveryservice:8761/eureka

---
spring:
  profiles: test